"""
Django settings for SchoolManagerProj SchoolManagerProject.

Generated by 'django-admin startSchoolManagerProject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoSchoolManagerProject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoSchoolManagerProject.com/en/5.1/ref/settings/
"""

from calendar import month
from pathlib import Path
import os 
from decouple import config  # Or use os.getenv()


# Build paths inside the SchoolManagerProject like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoSchoolManagerProject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m)-^f(0%i(w1_j3@slrgx7e2w&)il*^if#st05g0t+#zb2b96o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition
INSTALLED_APPS = [
    "daphne",
    "django_celery_results",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # dependancy apps 
    "corsheaders",
    'rest_framework',
    'rest_framework_simplejwt', 
    "anymail", # for brevo setup 
    # 'channels', 
    
    # custom apps 
    'academics' ,
    'core' ,
    'authUser' ,
    'director' ,
    'school' ,
    'student'  ,
    'teacher' ,
    'staff' ,
    'parent' ,
    'finance' ,
    'result' ,
    'attendanceanddevices' ,
]

MIDDLEWARE = [
    # cors header
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    
    # "django.middleware.common.CommonMiddleware",
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SchoolManagerProj.urls'

# rest framework config 
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # so as to be returning user instance
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
from datetime import timedelta


SIMPLE_JWT = {
  # It will work instead of the default serializer(TokenObtainPairSerializer).
  "TOKEN_OBTAIN_SERIALIZER": "authUser.serializers.CustomTokenObtainPairSerializer",
   'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=2),
    'ROTATE_REFRESH_TOKENS': False,
    # 'BLACKLIST_AFTER_ROTATION': True,
    
}


# 3. Allow JWT and ngrok headers
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    "authorization",
    "ngrok-skip-browser-warning",
]

# CORS_ALLOW_ALL_ORIGINS = True
# the hosts the host where to make request to here, thats your frontend host 
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000', #local 
    "https://1b69-102-89-76-171.ngrok-free.app", # ngrok
]

CSRF_TRUSTED_ORIGINS = [
    "https://1b69-102-89-76-171.ngrok-free.app", # ngrok 
    "https://19a1-102-89-76-171.ngrok-free.app", # ngrok 
]
ALLOWED_HOSTS = ["*"]
# The host allowed to host Django Back no need of https:// here 
# ALLOWED_HOSTS = ["19a1-102-89-76-171.ngrok-free.app",'127.0.0.1']  # ngrok and local


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SchoolManagerProj.wsgi.application'
ASGI_APPLICATION = 'SchoolManagerProj.asgi.application'

CHANNEL_LAYERS = {
    # 'default': {
    #      "BACKEND": "channels.layers.InMemoryChannelLayer",
    # },
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",

        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}



# Database
# https://docs.djangoSchoolManagerProject.com/en/5.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
    
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config("DB_NAME"),
        'USER': config("DB_USER"),
        'PASSWORD': config("DB_PASSWORD"),
        'HOST': '127.0.0.1',
        'PORT': '8002', # i set the local postegree to use this port it run auto matically on wondows start 
    }
}
# Password validation
# https://docs.djangoSchoolManagerProject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoSchoolManagerProject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoSchoolManagerProject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# STATICFILES_DIRS = [BASE_DIR,"second-app/build/static"]

MEDIA_URL="media/"
MEDIA_ROOT=os.path.join(BASE_DIR,"media")

# Default primary key field type
# https://docs.djangoSchoolManagerProject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# authentication 
AUTH_USER_MODEL = "authUser.User"

# Email Configurations
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"    for development environment 

#------------------------------------------------------------------------------------------------------
#                                       SMTP EMAIL CONFIGURATION
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')  # Load from .env
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # Load from .env
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

#------------------------------------------------------------------------------------------------------
#                         BREVO CONFIGURATIONS
#------------------------------------------------------------------------------------------------------
EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
BREVO_API_KEY = config("BREVO_API_KEY")
ANYMAIL = {
    "BREVO_API_KEY": BREVO_API_KEY,
}

#------------------------------------------------------------------------------------------------------
#                         TERMII CONFIGURATIONS
#------------------------------------------------------------------------------------------------------
TERMII_API_KEY = config("TERMII_API_KEY")
TERMII_SENDER_ID = config("TERMII_SENDER_ID")

#------------------------------------------------------------------------------------------------------
#                         CELERY CONFIGURATIONS
#------------------------------------------------------------------------------------------------------
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db' 
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'django-db' # cause i use  django-celery-result app for sroring tasks results 
# broker_connection_retry_on_startup = True
