# Generated by Django 5.1.4 on 2026-05-24 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=20)),
                ('mode', models.CharField(default='face', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('checkInTime', models.DateTimeField(blank=True, null=True)),
                ('checkOutTime', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BiometricIdentity',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('userType', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('director', 'Director')], max_length=20)),
                ('faceData', models.JSONField(default=list)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='biometric_profiles/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('uniqueCode', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('connectivity', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('type', models.CharField(choices=[('attendance', 'Attendance'), ('security', 'Security'), ('multi-purpose', 'Multi Purpose')], default='attendance', max_length=30)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('lastSeen', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
