# Generated by Django 5.1.4 on 2026-05-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceanddevices', '0003_alter_attendancerecord_school_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BiometricIdentity',
        ),
    ]
