# Generated by Django 5.1.4 on 2026-05-10 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceanddevices', '0005_biometricidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='biometricidentity',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
