"""
Django settings for backproj backproject.

Generated by 'django-admin startbackproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangobackproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangobackproject.com/en/5.1/ref/settings/
"""

from calendar import month
from pathlib import Path
import os 

# Build paths inside the backproject like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangobackproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m)-^f(0%i(w1_j3@slrgx7e2w&)il*^if#st05g0t+#zb2b96o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost','192.168.203.26','192.168.18.18','197.210.53.209','197.210.53.209:5173']

# Application definition
INSTALLED_APPS = [
    "daphne",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # dependancy apps 
    "corsheaders",
    'rest_framework',
    'rest_framework_simplejwt', 
    # 'channels', 
    
    # custom apps 
    'core',
    'account',
    'notifications',
    'authUser',
    'staff',
    'costomerService', 
]

MIDDLEWARE = [
    # cors header
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    # "django.middleware.common.CommonMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backproj.urls'

# rest framework config 
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # so as to be returning user instance
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
from datetime import timedelta

SIMPLE_JWT = {
  # It will work instead of the default serializer(TokenObtainPairSerializer).
  "TOKEN_OBTAIN_SERIALIZER": "authUser.serializers.CustomTokenObtainPairSerializer",
   'ACCESS_TOKEN_LIFETIME': timedelta(days=
                                      ),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=2),
    # 'ROTATE_REFRESH_TOKENS': False,
    # 'BLACKLIST_AFTER_ROTATION': True,
}


CORS_ALLOWED_ORIGINS = [
    "http://192.168.203.26:5173",
    "http://197.210.53.209:5173",
    'http://localhost:5173',
]
CORS_ALLOWED_ORIGIN_ALL = True

CSRF_TRUSTED_ORIGINS = [
   'http://192.168.203.26:5173',  # Replace with your ngrok URL
   'http://197.210.53.209:5173',  # Replace with your ngrok URL
   'http://192.168.18.18',  # Replace with your ngrok URL
]
ALLOWED_HOSTS = ['*']  # for dev only; replace with your LAN IP or domain in prod


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backproj.wsgi.application'
ASGI_APPLICATION = 'backproj.asgi.application'

CHANNEL_LAYERS = {
    # 'default': {
    #      "BACKEND": "channels.layers.InMemoryChannelLayer",
    # },
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}



# Database
# https://docs.djangobackproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# Password validation
# https://docs.djangobackproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangobackproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangobackproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# STATICFILES_DIRS = [BASE_DIR,"second-app/build/static"]

MEDIA_URL="media/"
MEDIA_ROOT=os.path.join(BASE_DIR,"media")

# Default primary key field type
# https://docs.djangobackproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# authentication 
AUTH_USER_MODEL = "authUser.User"

# Email Configurations
from decouple import config  # Or use os.getenv()
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')  # Load from .env
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # Load from .env
DEFAULT_FROM_EMAIL = 'noreflybackend@gmail.com'
# for dev and production 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# fake in console for development 
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# CELERY SETTINGS
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'