# Generated by Django 5.1.4 on 2026-05-24 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('school', '0001_initial'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionlog',
            name='promoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionlog',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_logs', to='school.school'),
        ),
        migrations.AddField(
            model_name='promotionlog',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_logs', to='school.session'),
        ),
        migrations.AddField(
            model_name='schoolsection',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='school.school'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.schoolsection'),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_rooms',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='teacher.teacher'),
        ),
        migrations.AddIndex(
            model_name='promotionlog',
            index=models.Index(fields=['session'], name='academics_p_session_a2621a_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionlog',
            index=models.Index(fields=['status'], name='academics_p_status_191eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionlog',
            index=models.Index(fields=['created_at'], name='academics_p_created_89ca11_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name', 'code'], name='subject_sub_name_08cfae_idx'),
        ),
    ]
