# Generated by Django 5.1.4 on 2026-05-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promotionlog',
            new_name='classroom_p_session_3cc4c1_idx',
            old_name='academics_p_session_a2621a_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionlog',
            new_name='classroom_p_status_326573_idx',
            old_name='academics_p_status_191eeb_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionlog',
            new_name='classroom_p_created_c58b90_idx',
            old_name='academics_p_created_89ca11_idx',
        ),
        migrations.AlterModelTable(
            name='promotionlog',
            table='classroom_promotionlog',
        ),
    ]
