# Generated by Django 5.1.4 on 2026-05-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_academics_p_session_a2621a_idx_classroom_p_session_3cc4c1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
    ]
