# Generated by Django 5.1.4 on 2026-05-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_subject_teachers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schoolsection',
            table='section_section',
        ),
    ]
