# Generated by Django 5.1.4 on 2026-05-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_schoolsection_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schoolsection',
            table='section_schoolsection',
        ),
    ]
