# Generated by Django 5.1.4 on 2026-05-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_schoolsection_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionlog',
            name='updated_at',
        ),
    ]
