# Generated by Django 5.1.4 on 2026-05-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_promotionlog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
