# Generated by Django 5.1.4 on 2026-05-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_promotionlog_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='section',
        ),
        migrations.RemoveField(
            model_name='schoolsection',
            name='school',
        ),
    ]
