# Generated by Django 5.1.4 on 2026-05-24 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_classroom_section_remove_schoolsection_school'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.schoolsection'),
        ),
        migrations.AddField(
            model_name='schoolsection',
            name='school',
            field=models.ForeignKey(default='cc8c2ed8-5daa-41f0-9af3-9a73b691c796', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='school.school'),
            preserve_default=False,
        ),
    ]
