# Generated by Django 5.1.4 on 2026-05-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_classroom_section_schoolsection_school'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='promotionlog',
            name='classroom_p_session_3cc4c1_idx',
        ),
        migrations.RemoveField(
            model_name='promotionlog',
            name='promoted_by',
        ),
        migrations.RemoveField(
            model_name='promotionlog',
            name='school',
        ),
        migrations.RemoveField(
            model_name='promotionlog',
            name='session',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='class_rooms',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
    ]
