# Generated by Django 5.1.4 on 2026-05-24 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_remove_promotionlog_classroom_p_session_3cc4c1_idx_and_more'),
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionlog',
            name='promoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionlog',
            name='school',
            field=models.ForeignKey(default='cc8c2ed8-5daa-41f0-9af3-9a73b691c796', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_logs', to='school.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotionlog',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_logs', to='school.session'),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_rooms',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, default='cc8c2ed8-5daa-41f0-9af3-9a73b691c796', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.school'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='promotionlog',
            index=models.Index(fields=['session'], name='classroom_p_session_3cc4c1_idx'),
        ),
    ]
