# Generated by Django 5.1.4 on 2026-05-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_classroom_form_teacher_subject_teachers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_rooms',
        ),
    ]
