# Generated by Django 5.1.4 on 2026-06-04 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_subject_class_rooms'),
        ('teacher', '0003_remove_teacher_class_room_remove_teacher_form_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_assignments', to='teacher.teacher'),
        ),
    ]
