# Generated by Django 5.1.4 on 2026-06-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_teachingassignment_teacher'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(blank=True, default='cc8c2ed8-5daa-41f0-9af3-9a73b691c796', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school.school'),
            preserve_default=False,
        ),
    ]
