# Generated by Django 5.1.4 on 2026-01-27 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
