# Generated by Django 5.1.4 on 2026-05-10 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('promoted_students', models.PositiveIntegerField(default=0)),
                ('skipped_students', models.PositiveIntegerField(default=0)),
                ('failed_students', models.PositiveIntegerField(default=0)),
                ('total_batches', models.PositiveIntegerField(default=1)),
                ('processed_batches', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('mappings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_promotions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_logs', to='school.school')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_logs', to='school.session')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session'], name='classroom_p_session_3cc4c1_idx'), models.Index(fields=['status'], name='classroom_p_status_326573_idx'), models.Index(fields=['created_at'], name='classroom_p_created_c58b90_idx')],
            },
        ),
    ]
