# Generated by Django 5.1.4 on 2026-02-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_initial'),
        ('teacher', '0008_remove_teacher_form_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formclasses', to='teacher.teacher'),
        ),
    ]
