# Generated by Django 5.1.4 on 2026-05-24 13:44

import authUser.models
import django.contrib.auth.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('date_of_birth', models.DateField(verbose_name='DOB')),
                ('id_type', models.CharField(choices=[('national_id', 'National Id Card'), ('passport', 'International Passport'), ('driving_licence', 'Driving Licence')], default='national_id', max_length=50, verbose_name='Id Type')),
                ('id_number', models.CharField(max_length=70, verbose_name='Id Number ')),
                ('address_pic', models.ImageField(null=True, upload_to=authUser.models.upload_kyc_image, verbose_name='id owner pic')),
                ('user_pic', models.ImageField(null=True, upload_to=authUser.models.upload_kyc_image, verbose_name='id owner pic')),
                ('id_card_pic', models.ImageField(null=True, upload_to=authUser.models.upload_kyc_image, verbose_name='id pic')),
                ('signature_pic', models.ImageField(null=True, upload_to=authUser.models.upload_kyc_image, verbose_name='Signature')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=50, null=True, verbose_name='gender')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='city')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date submitted')),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYCs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PendingEmail',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('verification_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Verification Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pins', models.CharField(blank=True, max_length=255, verbose_name='Pins')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UserPins',
                'verbose_name_plural': 'UserPins',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='code')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UserCode',
                'verbose_name_plural': 'UserCode',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('username', models.CharField(editable=False, max_length=100, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='middle Name ')),
                ('phone_number', models.CharField(blank=True, max_length=14, verbose_name='phone_number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('picture', models.ImageField(default='default.png', upload_to=authUser.models.upload_user_image, verbose_name='user pic')),
                ('role', models.CharField(blank=True, default='Admin', max_length=50, verbose_name='role')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='gender')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('refarrel_code', models.CharField(blank=True, editable=False, max_length=6, verbose_name='invitation code')),
                ('kyc_submitted', models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED'), ('PENDING', 'PENDING')], default=' UNVERIFIED ', max_length=50, verbose_name='kyc submitted')),
                ('kyc_confirmed', models.BooleanField(default=False, verbose_name=' kyc varified ')),
                ('email_varified', models.BooleanField(default=False, verbose_name='varified email')),
                ('otp_required', models.BooleanField(default=True, verbose_name='OTP Required')),
                ('pin_set', models.BooleanField(default=False, verbose_name='Payment Pin Set')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active account')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('refarrels', models.ManyToManyField(blank=True, related_name='inviter', to=settings.AUTH_USER_MODEL, verbose_name='refarrels')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
