# Generated by Django 5.1.4 on 2024-12-06 11:33

import authUser.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0002_delete_kyc_user_email_varified_user_kyc_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name ')),
                ('last_name', models.CharField(max_length=100, verbose_name='last Name ')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='middle Name ')),
                ('date_of_birth', models.DateField(verbose_name='DOB')),
                ('id_type', models.CharField(choices=[('national-id-card', 'National Id Card'), ('international-passport', 'International Passport'), ('driving-licence', 'Driving Licence')], default='national-id-card', max_length=50, verbose_name='Id Type')),
                ('id_number', models.CharField(max_length=70, verbose_name='Id Number ')),
                ('address_pic', models.ImageField(null=True, upload_to=authUser.models.upload_kyc_image, verbose_name='id owner pic')),
                ('picture', models.ImageField(null=True, upload_to=authUser.models.upload_kyc_image, verbose_name='id owner pic')),
                ('id_card_pic', models.ImageField(null=True, upload_to=authUser.models.upload_kyc_image, verbose_name='id pic')),
                ('signature', models.ImageField(null=True, upload_to=authUser.models.upload_kyc_image, verbose_name='Signature')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=50, null=True, verbose_name='gender')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='city')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date submitted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='account owner')),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYCs',
                'ordering': ['-date'],
            },
        ),
    ]
