# Generated by Django 5.1.4 on 2026-05-14 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0002_alter_pendingemail_id'),
        ('school', '0004_schoolpermission_schoolrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='school.schoolrole'),
        ),
    ]
