# Generated by Django 5.1.4 on 2026-06-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_alerts',
            field=models.BooleanField(default=True, verbose_name='Login Alerts'),
        ),
        migrations.AddField(
            model_name='user',
            name='session_timeout',
            field=models.CharField(blank=True, choices=[('30m', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('24h', '24 Hours'), ('2d', '2 Days')], max_length=10, verbose_name='Session Timeout'),
        ),
    ]
