# Generated by Django 5.1.4 on 2026-05-14 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0003_user_school_role'),
        ('school', '0004_schoolpermission_schoolrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default='cc8c2ed8-5daa-41f0-9af3-9a73b691c796', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='school.school'),
            preserve_default=False,
        ),
    ]
