# Generated by Django 5.1.4 on 2026-06-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0003_user_login_alerts_user_session_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_timeout',
            field=models.CharField(blank=True, choices=[('30m', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('24h', '24 Hours'), ('2d', '2 Days')], default='1d', max_length=10, verbose_name='Session Timeout'),
        ),
    ]
