# Generated by Django 5.1.4 on 2024-12-06 11:39

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0004_user_refarrel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refarrel_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLXZ123456789', editable=False, length=6, max_length=6, prefix='', unique=True, verbose_name='invitation code'),
        ),
    ]
