# Generated by Django 5.1.4 on 2024-12-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0005_alter_user_refarrel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_pin',
            field=models.CharField(blank=True, max_length=4, verbose_name='Payment Pin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, unique=True, verbose_name='phone_number'),
        ),
    ]
