# Generated by Django 5.1.4 on 2024-12-06 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0006_user_payment_pin_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, unique=True, verbose_name='phone_number'),
        ),
    ]
