# Generated by Django 5.1.4 on 2024-12-07 09:55

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0007_alter_kyc_id_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refarrel_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLXZ123456789', blank=True, editable=False, length=6, max_length=6, prefix='', unique=True, verbose_name='invitation code'),
        ),
    ]
