# Generated by Django 5.1.4 on 2024-12-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0011_alter_user_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, verbose_name='phone_number'),
        ),
    ]
