# Generated by Django 5.1.4 on 2024-12-28 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0014_alter_kyc_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_kyc', to=settings.AUTH_USER_MODEL, verbose_name='account owner'),
        ),
    ]
