# Generated by Django 5.1.4 on 2025-06-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0018_user_payment_pin_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transection_permission',
        ),
        migrations.AddField(
            model_name='user',
            name='can_transect',
            field=models.BooleanField(default=True, verbose_name='can transect'),
        ),
    ]
