# Generated by Django 5.1.4 on 2025-11-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0024_rename_code_verificationcode_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationcode',
            old_name='codes',
            new_name='code',
        ),
    ]
