# Generated by Django 5.1.4 on 2025-11-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0026_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active account'),
        ),
    ]
