# Generated by Django 5.1.4 on 2025-11-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0028_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('verification_code', models.CharField(blank=True, max_length=255, verbose_name='Verification Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
