# Generated by Django 5.1.4 on 2025-11-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0029_pendingemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingemail',
            name='verification_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Verification Code'),
        ),
    ]
