# Generated by Django 5.1.4 on 2025-11-29 19:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0030_alter_pendingemail_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingemail',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
    ]
