# Generated by Django 5.1.4 on 2026-01-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0031_alter_pendingemail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='log_with_otp',
            field=models.BooleanField(default=True, verbose_name='Login with OTP'),
        ),
    ]
