# Generated by Django 5.1.4 on 2026-01-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0032_user_log_with_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='log_with_otp',
            new_name='otp_required',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code_set',
        ),
    ]
