# Generated by Django 5.1.4 on 2026-01-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0033_rename_log_with_otp_user_otp_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_required',
            field=models.BooleanField(default=True, verbose_name='OTP Required'),
        ),
    ]
