# Generated by Django 5.1.4 on 2026-01-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0034_alter_user_otp_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_confirmed',
            field=models.BooleanField(default=False, verbose_name=' kyc varified '),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_submitted',
            field=models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED'), ('PENDING', 'PENDING')], default=' UNVERIFIED ', max_length=50, verbose_name='kyc submitted'),
        ),
    ]
