# Generated by Django 5.1.4 on 2026-01-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0036_user_role_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='Admin', max_length=50, verbose_name='role'),
        ),
    ]
