# Generated by Django 5.1.4 on 2026-01-29 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0039_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpins',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PinCode',
        ),
    ]
