# Generated by Django 5.1.4 on 2026-01-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
