# Generated by Django 5.1.4 on 2026-01-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_director_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='role',
            field=models.CharField(blank=True, default='Director', max_length=100),
        ),
    ]
