# Generated by Django 5.1.4 on 2026-01-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_alter_director_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
    ]
