# Generated by Django 5.1.4 on 2026-01-27 15:26

import django.db.models.deletion
import school.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0005_director_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('ref_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, default='school_default.png', null=True, upload_to=school.models.upload_school_logo)),
                ('tag', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('on_delete_request', models.BooleanField(default=False)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directorschools', to='director.director')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDeleteRequest',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delete_requests', to='school.school')),
            ],
        ),
    ]
