# Generated by Django 5.1.4 on 2025-11-25 10:56

import django.db.models.deletion
import school.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.CharField(default=school.models.uuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('ref_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, default='school_default.png', null=True, upload_to=school.models.upload_school_logo)),
                ('tag', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schools', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSection',
            fields=[
                ('id', models.CharField(default=school.models.uuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.CharField(default=school.models.uuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school.schoolsection')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(default=school.models.uuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, default='student_default.png', null=True, upload_to=school.models.upload_student_pic, verbose_name='student pic')),
                ('admission_number', models.CharField(max_length=120, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='school.classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(default=school.models.uuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, default='teacher_default.png', null=True, upload_to=school.models.upload_teacher_pic, verbose_name='teacher pic')),
                ('staff_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.school')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers', to='school.schoolsection')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(default=school.models.uuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('class_room', models.ManyToManyField(blank=True, related_name='subjects', to='school.classroom')),
                ('teacher', models.ManyToManyField(blank=True, related_name='subjects', to='school.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.teacher'),
        ),
    ]
