# Generated by Django 5.1.4 on 2026-05-24 13:44

import django.db.models.deletion
import school.models
import shortuuid.django_fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('ref_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, default='school_default.png', null=True, upload_to=school.models.upload_school_logo)),
                ('tag', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('on_delete_request', models.BooleanField(default=False)),
                ('lock_records', models.BooleanField(default=False)),
                ('grading_system', models.CharField(choices=[('standard', 'Standard (A-F)'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('auto_promotion', models.BooleanField(default=False)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directorschools', to='director.director')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('paymentDueDate', models.IntegerField(default=15)),
                ('onlinePayment', models.BooleanField(default=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDeleteRequest',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delete_requests', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPermission',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRole',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='school.schoolpermission')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Form', 'Form'), ('Letter', 'Letter'), ('Report', 'Report'), ('Transcript', 'Transcript'), ('Certificate', 'Certificate'), ('Admission', 'Admission'), ('Other', 'Other')], default='Default', max_length=100)),
                ('fileType', models.CharField(blank=True, max_length=100)),
                ('isConfigured', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=True)),
                ('htmlContent', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', length=12, max_length=20, prefix='', primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('SUSPEND', 'SUSPEND'), ('LOGIN', 'LOGIN'), ('PAYMENT', 'PAYMENT')], db_index=True, max_length=20)),
                ('module', models.CharField(choices=[('STUDENTS', 'STUDENTS'), ('TEACHERS', 'TEACHERS'), ('STAFF', 'STAFF'), ('ACADEMICS', 'ACADEMICS'), ('FINANCE', 'FINANCE'), ('SETTINGS', 'SETTINGS'), ('PROFILE', 'PROFILE')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='school.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='school_acti_user_id_084956_idx'), models.Index(fields=['module'], name='school_acti_module_f39aee_idx'), models.Index(fields=['action'], name='school_acti_action_cbf930_idx'), models.Index(fields=['created_at'], name='school_acti_created_2729bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchoolBankAccount',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=150)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='school.financesettings')),
            ],
            options={
                'unique_together': {('bank_name', 'account_number', 'is_default')},
            },
        ),
    ]
