# Generated by Django 5.1.4 on 2026-06-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(choices=[('STUDENTS', 'STUDENTS'), ('TEACHERS', 'TEACHERS'), ('STAFF', 'STAFF'), ('ACADEMICS', 'ACADEMICS'), ('FINANCE', 'FINANCE'), ('SETTINGS', 'SETTINGS'), ('PROFILE', 'PROFILE'), ('ROLES', 'ROLES'), ('PERMISSIONS', 'PERMISSIONS')], db_index=True, max_length=30),
        ),
    ]
