# Generated by Django 5.1.4 on 2025-11-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='section',
        ),
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='school.schoolsection'),
        ),
    ]
