# Generated by Django 5.1.4 on 2026-05-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_id_alter_schooldeleterequest_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='picture',
        ),
    ]
