# Generated by Django 5.1.4 on 2026-06-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_activitylog_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='max_marks',
            field=models.JSONField(blank=True, default={'ca1': 20, 'ca2': 20, 'exam': 60}, null=True),
        ),
    ]
