# Generated by Django 5.1.4 on 2026-05-14 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_school_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='school.schoolpermission')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='school.school')),
            ],
        ),
    ]
