# Generated by Django 5.1.4 on 2026-06-18 18:23

import school.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_max_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='max_marks',
            field=models.JSONField(blank=True, default=school.models.d_marks, null=True),
        ),
    ]
