# Generated by Django 5.1.4 on 2025-11-25 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_email_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='section',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='school.schoolsection'),
        ),
    ]
