# Generated by Django 5.1.4 on 2026-05-18 16:24

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_schoolpermission_schoolrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', length=12, max_length=20, prefix='', primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('SUSPEND', 'SUSPEND'), ('LOGIN', 'LOGIN'), ('PAYMENT', 'PAYMENT')], db_index=True, max_length=20)),
                ('module', models.CharField(choices=[('STUDENTS', 'STUDENTS'), ('TEACHERS', 'TEACHERS'), ('STAFF', 'STAFF'), ('ACADEMICS', 'ACADEMICS'), ('FINANCE', 'FINANCE'), ('SETTINGS', 'SETTINGS'), ('PROFILE', 'PROFILE')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='school.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='school_acti_user_id_084956_idx'), models.Index(fields=['module'], name='school_acti_module_f39aee_idx'), models.Index(fields=['action'], name='school_acti_action_cbf930_idx'), models.Index(fields=['created_at'], name='school_acti_created_2729bf_idx')],
            },
        ),
    ]
