# Generated by Django 5.1.4 on 2025-11-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_student_email_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
