# Generated by Django 5.1.4 on 2025-11-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='staff_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
