# Generated by Django 5.1.4 on 2025-11-28 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_parents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parents',
            options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.AddField(
            model_name='school',
            name='director_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='director email'),
        ),
        migrations.AddField(
            model_name='school',
            name='director_fullname',
            field=models.CharField(default='director@gmail.com', max_length=150, verbose_name='director name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='director_password',
            field=models.CharField(default='director@gmail.com', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
