# Generated by Django 5.1.4 on 2025-11-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_parents_options_school_director_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='director_email',
            field=models.EmailField(default='emailtyu&gmail.com', max_length=254, verbose_name='director email'),
            preserve_default=False,
        ),
    ]
