# Generated by Django 5.1.4 on 2025-11-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_school_director_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='director_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='director email'),
        ),
    ]
