# Generated by Django 5.1.4 on 2025-11-29 19:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_school_director_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parents',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schoolsection',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
    ]
