# Generated by Django 5.1.4 on 2025-11-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_classroom_class_teacher_alter_parents_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='director_password',
        ),
        migrations.AddField(
            model_name='school',
            name='director_phone',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
