# Generated by Django 5.1.4 on 2026-01-27 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0002_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('class_room', models.ManyToManyField(blank=True, related_name='subjects', to='classroom.classroom')),
                ('teacher', models.ManyToManyField(blank=True, related_name='subjects', to='teacher.teacher')),
            ],
        ),
    ]
