# Generated by Django 5.1.4 on 2026-01-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
