# Generated by Django 5.1.4 on 2026-01-31 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('subject', '0003_subject_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, default='c1d544ad-5ea2-42bc-ba86-1131fe9a6b0a', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.school'),
            preserve_default=False,
        ),
    ]
