# Generated by Django 5.1.4 on 2026-01-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='role',
            field=models.CharField(default='Parent', max_length=50),
        ),
    ]
