# Generated by Django 5.1.4 on 2026-02-04 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parents',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='students',
        ),
        migrations.AddField(
            model_name='parents',
            name='relation_ship',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parents',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
