# Generated by Django 5.1.4 on 2026-02-04 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_rename_first_name_parents_full_name_and_more'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='school.school'),
        ),
    ]
