# Generated by Django 5.1.4 on 2026-02-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0005_alter_parents_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
