# Generated by Django 5.1.4 on 2024-12-06 11:25

import authUser.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KYC',
        ),
        migrations.AddField(
            model_name='user',
            name='email_varified',
            field=models.BooleanField(default=False, verbose_name='varified email'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_confirmed',
            field=models.BooleanField(default=False, verbose_name='varified'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_submitted',
            field=models.CharField(choices=[('VERIIFED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED'), ('PENDING', 'PENDING')], default='UNVERIFIED', max_length=50, verbose_name='verification submitted'),
        ),
        migrations.AddField(
            model_name='user',
            name='lock_password',
            field=models.CharField(blank=True, max_length=6, verbose_name='unlock password'),
        ),
        migrations.AddField(
            model_name='user',
            name='log_with_otp',
            field=models.BooleanField(default=True, verbose_name='login with otp'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=authUser.models.upload_user_image, verbose_name='user pic'),
        ),
        migrations.AddField(
            model_name='user',
            name='refarrels',
            field=models.ManyToManyField(blank=True, related_name='inviter', to=settings.AUTH_USER_MODEL, verbose_name='refarrels'),
        ),
        migrations.AddField(
            model_name='user',
            name='transection_permission',
            field=models.CharField(choices=[('SUSP', 'SUSPENDED'), ('NORM', 'NORMAL')], default='NORM', max_length=50, verbose_name='can transect'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
