# Generated by Django 5.1.4 on 2024-12-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0009_alter_kyc_user_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='unlock email_verification_code'),
        ),
    ]
