# Generated by Django 5.1.4 on 2024-12-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0010_user_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='email_verification_code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_confirmed',
            field=models.BooleanField(default=False, verbose_name='kyc varified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_submitted',
            field=models.CharField(choices=[('VERIIFED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED'), ('PENDING', 'PENDING')], default='UNVERIFIED', max_length=50, verbose_name='kyc submitted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lock_password',
            field=models.CharField(blank=True, max_length=6, verbose_name='locking password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='refarrel_code',
            field=models.CharField(blank=True, editable=False, max_length=6, verbose_name='invitation code'),
        ),
    ]
