# Generated by Django 5.1.4 on 2024-12-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0012_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='signature',
            new_name='signature_pic',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='picture',
            new_name='user_pic',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='last_name',
        ),
        migrations.AddField(
            model_name='kyc',
            name='full_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Full Name '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, unique=True, verbose_name='phone_number'),
        ),
    ]
