# Generated by Django 5.1.4 on 2025-06-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0017_alter_kyc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_pin_set',
            field=models.BooleanField(default=False, verbose_name='Payment Pin Set'),
        ),
    ]
