# Generated by Django 5.1.4 on 2025-06-30 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0019_remove_user_transection_permission_user_can_transect'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pins', models.CharField(blank=True, max_length=5, verbose_name='Action Pin')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staffpins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StaffPins',
                'verbose_name_plural': 'StaffPinss',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
