# Generated by Django 5.1.4 on 2025-11-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0020_staffpins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffpins',
            options={'managed': True, 'verbose_name': 'StaffPins', 'verbose_name_plural': 'StaffPins'},
        ),
        migrations.AlterField(
            model_name='staffpins',
            name='pins',
            field=models.CharField(blank=True, max_length=255, verbose_name='Action Pin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='email_verification_code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_submitted',
            field=models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED'), ('PENDING', 'PENDING')], default='UNVERIFIED', max_length=50, verbose_name='kyc submitted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_pin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Payment Pin'),
        ),
    ]
