# Generated by Django 5.1.4 on 2025-11-22 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0021_alter_staffpins_options_alter_staffpins_pins_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='payment_pin_set',
            new_name='pin_set',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_transect',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lock_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='log_with_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_pin',
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='middle Name '),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_set',
            field=models.CharField(blank=True, max_length=255, verbose_name='verification_code'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_type',
            field=models.CharField(choices=[('national_id', 'National Id Card'), ('passport', 'International Passport'), ('driving_licence', 'Driving Licence')], default='national_id', max_length=50, verbose_name='Id Type'),
        ),
        migrations.CreateModel(
            name='UserPins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pins', models.CharField(blank=True, max_length=255, verbose_name='Pins')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userpins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserPins',
                'verbose_name_plural': 'UserPins',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='code')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verificationcode', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserCode',
                'verbose_name_plural': 'UserCode',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='StaffPins',
        ),
    ]
