# Generated by Django 5.1.4 on 2025-11-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0022_rename_payment_pin_set_user_pin_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, verbose_name='phone_number'),
        ),
    ]
