# Generated by Django 5.1.4 on 2025-11-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0023_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationcode',
            old_name='code',
            new_name='codes',
        ),
    ]
