# Generated by Django 5.1.4 on 2026-01-27 15:26

import django.db.models.deletion
import staff.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRole',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('security', 'Security'), ('cleaner', 'Cleaner'), ('driver', 'Driver')], default='security', max_length=100)),
                ('rank', models.CharField(choices=[('header', 'Header'), ('vice', 'Vice'), ('standerd', 'Standerd')], default='standerd', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('date_assined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('picture', models.ImageField(blank=True, default='staff_default.png', null=True, upload_to=staff.models.upload_staff_pic, verbose_name='staff pic')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(blank=True, default='Staff', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('staff_id', models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('activity_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='staff.activityrole')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='school.school')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
