# Generated by Django 5.1.4 on 2026-02-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bankdetails'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bank_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.bankdetails'),
        ),
        migrations.AddField(
            model_name='staff',
            name='nin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
