# Generated by Django 5.1.4 on 2026-01-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, default='Staff', max_length=100),
        ),
    ]
