# Generated by Django 5.1.4 on 2026-01-20 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('staff', '0002_staff_address_staff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRole',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('security', 'Security'), ('cleaner', 'Cleaner'), ('driver', 'Driver')], default='security', max_length=100)),
                ('rank', models.CharField(choices=[('header', 'Header'), ('vice', 'Vice'), ('standerd', 'Standerd')], default='standerd', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='school.school'),
        ),
        migrations.AddField(
            model_name='staff',
            name='activity_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='staff.activityrole'),
        ),
    ]
