# Generated by Django 5.1.4 on 2026-05-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_activityrole_id_alter_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrole',
            name='role',
            field=models.CharField(choices=[('academic', 'Academic'), ('security', 'Security'), ('cleaner', 'Cleaner'), ('driver', 'Driver')], default='security', max_length=100),
        ),
    ]
