# Generated by Django 5.1.4 on 2026-01-20 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_activityrole_alter_staff_gender_alter_staff_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrole',
            name='date_assined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
