# Generated by Django 5.1.4 on 2026-01-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default='Student', max_length=50),
        ),
    ]
