# Generated by Django 5.1.4 on 2026-06-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('promoted', 'Promoted'), ('transferred', 'Transferred'), ('demoted', 'Demoted'), ('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn')], db_index=True, default='enrolled', max_length=20),
        ),
    ]
