# Generated by Django 5.1.4 on 2026-06-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentclassenrollment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['joined_at']},
        ),
    ]
