# Generated by Django 5.1.4 on 2026-05-14 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroom_id_alter_promotionlog_id'),
        ('parent', '0002_alter_parents_id'),
        ('school', '0004_schoolpermission_schoolrole'),
        ('student', '0002_alter_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(db_index=True, default='Student', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('promoted', 'Promoted'), ('transfered', 'Transfered'), ('demoted', 'Demoted'), ('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn')], db_index=True, default='enrolled', max_length=20),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'admission_number'], name='student_stu_school__691773_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'first_name'], name='student_stu_school__0a85ae_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'joined_at'], name='student_stu_school__d7b53d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentclassenrollment',
            index=models.Index(fields=['student', 'class_room', 'session', 'status'], name='student_stu_student_21c7dd_idx'),
        ),
    ]
