# Generated by Django 5.1.4 on 2026-05-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroom_id_alter_promotionlog_id'),
        ('school', '0004_schoolpermission_schoolrole'),
        ('student', '0003_alter_student_email_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentclassenrollment',
            name='student_stu_student_21c7dd_idx',
        ),
        migrations.AddIndex(
            model_name='studentclassenrollment',
            index=models.Index(fields=['student', 'status'], name='student_stu_student_d2d49b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentclassenrollment',
            index=models.Index(fields=['student', 'class_room', 'status'], name='student_stu_student_95b8aa_idx'),
        ),
    ]
