# Generated by Django 5.1.4 on 2026-05-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_studentclassenrollment_student_stu_student_21c7dd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
