# Generated by Django 5.1.4 on 2026-05-10 14:08

import django.db.models.deletion
import teacher.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('core', '0001_initial'),
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('picture', models.ImageField(blank=True, default='teacher_default.png', null=True, upload_to=teacher.models.upload_teacher_pic, verbose_name='teacher pic')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(default='Teacher', max_length=50)),
                ('nin', models.CharField(blank=True, max_length=50)),
                ('salary', models.CharField(blank=True, max_length=20)),
                ('staff_id', models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('bank_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='core.bankdetails')),
                ('class_room', models.ManyToManyField(blank=True, related_name='teachers', to='classroom.classroom')),
                ('form_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_teacher', to='classroom.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.school')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisplinaryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinaryRecords', to='teacher.teacher')),
            ],
        ),
    ]
