# Generated by Django 5.1.4 on 2026-02-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_nin_teacher_salary_teacherbankdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
