# Generated by Django 5.1.4 on 2026-05-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_room',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='form_class',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
    ]
