# Generated by Django 5.1.4 on 2026-02-07 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherbankdetails',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='bank_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='teacher.teacherbankdetails'),
        ),
    ]
