# Generated by Django 5.1.4 on 2026-02-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacherbankdetails_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
