# Generated by Django 5.1.4 on 2026-02-07 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bankdetails'),
        ('teacher', '0005_alter_teacher_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bank_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='core.bankdetails'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='TeacherBankDetails',
        ),
    ]
