# Generated by Django 5.1.4 on 2026-02-08 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_initial'),
        ('teacher', '0006_alter_teacher_bank_details_alter_teacher_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='form_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_teacher', to='classroom.classroom'),
        ),
    ]
