# Generated by Django 5.1.4 on 2026-02-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_teacher_form_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='form_class',
        ),
    ]
